org: winkreact
service: wink-react-native-back-end

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/UserTable
        - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/TransactionTable
functions:
  createUser:
    handler: src/user/user.addUser
    events:
      - httpApi:
          path: /user
          method: post
  getAllUsers:
    handler: src/user/user.getAllUsers
    events:
      - httpApi:
          path: /user
          method: get
  getUser:
    handler: src/user/user.getUser
    events:
      - httpApi:
          path: /user/{userId}
          method: get
  updateUser:
    handler: src/user/user.updateUser
    events:
      - httpApi:
          path: /user/{userId}
          method: put
  deleteUser:
    handler: src/user/user.deleteUser
    events:
      - httpApi:
          path: /user/{userId}
          method: delete
  createTransaction:
    handler: src/transaction/transaction.addTransaction
    events:
      - httpApi:
          path: /transaction
          method: post
  getAllTransactions:
    handler: src/transaction/transaction.getAllTransactions
    events:
      - httpApi:
          path: /transaction
          method: get
  getTransaction:
    handler: src/transaction/transaction.getTransaction
    events:
      - httpApi:
          path: /transaction/{transactionId}
          method: get
  updateTransaction:
    handler: src/transaction/transaction.updateTransaction
    events:
      - httpApi:
          path: /transaction/{transactionId}
          method: put
  deleteTransaction:
    handler: src/transaction/transaction.deleteTransaction
    events:
      - httpApi:
          path: /transaction/{transactionId}
          method: delete
resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH

    TransactionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TransactionTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: transactionId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: transactionId
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
